apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: olo-watched-ns2

bases:
- ../../../overlays/watch-another-namespace/olo-watched-ns

patchesStrategicMerge:
- watched-roles.yaml