apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: olo-ns


resources:
- ../../overlays/watch-all-namespaces
patches:
- path: olo-leader-election-cluster-rolebinding.yaml
- path: olo-manager-cluster-rolebinding.yaml
