apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: open-liberty-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: open-liberty-operator
  name: olo-liberty-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: olo-liberty-proxy-role
subjects:
- kind: ServiceAccount
  name: olo-liberty-proxy
  namespace: olo-system
