apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: open-liberty-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: open-liberty-operator
    config.openshift.io/inject-trusted-cabundle: "true"
  name: olo-trusted-ca
