apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: open-liberty-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: open-liberty-operator
  name: olo-liberty-proxy
