apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: open-liberty-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: open-liberty-operator
  name: olo-liberty-proxy-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - serviceaccounts
  verbs:
  - create
  - get
  - update
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  - certificates
  verbs:
  - create
  - get
  - update
  - list
  - watch
