apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: olo-ns


resources:
- ../../../base
patches:
- path: olo-deployment.yaml
- path: role1.yaml
- path: role2.yaml
- path: role3.yaml
- path: role4.yaml
- path: olo-sa.yaml
