---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-openliberty-io-apps-openliberty-io-v1-openlibertyapplication
  failurePolicy: Fail
  name: vopenlibertyapplication-v1.kb.io
  rules:
  - apiGroups:
    - apps.openliberty.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openlibertyapplications
  sideEffects: None
