= Installing the Open Liberty Operator using kustomize

This directory contains configuration files that helps installing the Open Liberty operator
using `kustomize` with the Kubernetes command-line interface (CLI) (`kubectl`). These configurations
are useful when the cluster is not a Red Hat® OpenShift® Container Platform cluster or when
Operator Lifecycle Manager is not being used.

== Installing and watching own namespace

=== base
The base configuration installs the operator into the 'open-liberty' namespace,
and the operator watches for Open Liberty custom resource instances only in its own namespace.
Create a namespace called 'open-liberty' for the operator.
To install, run: `kubectl apply --server-side -k base` and to uninstall, run: `kubectl delete -k base`

=== examples/watch-own-namespace
This example overlay demonstrates how to modify the base configuration to install the operator and have it
watch a namespace other than 'open-liberty'. Create a namespace called 'olo-ns' for the operator.
To install the operator into the 'olo-ns' namespace, run: `kubectl apply --server-side -k examples/watch-own-namespace`

== Installing and watching another namespace

=== overlays/watch-another-namespace
This overlay installs the operator into the namespace 'olo-ns', but configures it to
watch for Open Liberty custom resource instances in a different namespace called 'olo-watched-ns'.
Because this overlay installs resources into two different namespaces, the namespace must not be specified
in the kustomize.yaml file. To install, run:  `kubectl apply --server-side -k overlays/watch-another-namespace`

=== examples/watch-another-namespace
This example overlay builds on the previous example, but demonstrates how to change
the install and watched namespaces. In this case, the operator is installed into 'olo-ns2'
and watches for resources in 'olo-watched-ns2'. To install run: `kubectl apply --server-side -k
examples/watch-another-namespace`

== Installing and watching all namespaces

=== overlays/watch-all-namespaces
This overlay installs the operator into the 'open-liberty' namespace,
but configures it to watch for Open Liberty custom resource instances in any namespaces.
Compared to the base configuration, this overlay requires additional ClusterRoles and ClusterRoleBindings.
To install, run: `kubectl apply --server-side -k overlays/watch-all-namespaces`

=== examples/watch-all-namespaces
This example overlay builds on the previous example and demonstrates how to change
the namespace that the operator installs into. In this example, the operator installs
into a namespace that is called 'olo-ns' and watches for Open Liberty custom resource
instances in any namespaces. To install, run: `kubectl apply --server-side -k examples/watch-all-namespaces`