{
 "title": "Liberty-Metrics-G5-20190521",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": "base:cpu_available_processors" },
   {
    "name": "servlet",
    "query": "{__name__=~\"vendor:servlet.*_response_time_total_seconds\",service=~`[[service]]`}"
   },
   {
    "name": "dur",
    "label": "moving average",
    "query": "[1m],[5m],[10m],[30m],[1h],[1d],[7d]"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available CPU Processors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "base:cpu_available_processors{service=~`[[service]]`}",
       "legendFormat": "service: {{service}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "CPU Load Percent",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "base:cpu_process_cpu_load_percent{service=~`[[service]]`}",
       "legendFormat": "service: {{service}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "CPU System Load Average",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "base:cpu_system_load_average{service=~`[[service]]`}",
       "legendFormat": "service: {{service}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Maximum Heap Size",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "base:memory_max_heap_bytes{service=~`[[service]]`}"
      }
     ]
    },
    {
     "title": "Heap Usage Percentage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(base:memory_used_heap_bytes{service=~`[[service]]`}/base:memory_max_heap_bytes{service=~`[[service]]`})",
       "legendFormat": "service: {{service}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Servlets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "{__name__=~\"vendor:servlet.*_request_total\",service=~`[[service]]`}"
      }
     ]
    },
    {
     "title": "Request Count for [[servlet]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor:servlet_[[servlet]]_request_total{service=~`[[service]]`}",
       "legendFormat": "service: {{service}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Response Time for [[servlet]] [[dur]] moving average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor:servlet_[[servlet]]_response_time_total_seconds{service=~`[[service]]`}[[dur]])/rate(vendor:servlet_[[servlet]]_request_total{service=~`[[service]]`}[[dur]])",
       "legendFormat": "service: {{service}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"vendor:connectionpool_.*_free_connections\",service=~`[[service]]`}",
       "legendFormat": "name: {{__name__}} service: {{service}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Connection Handles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"vendor:connectionpool_.*_connection_handles\",service=~`[[service]]`}",
       "legendFormat": "name: {{__name__}} service: {{service}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Create Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"vendor:connectionpool_.*_create_total\",service=~`[[service]]`}",
       "legendFormat": "name: {{__name__}} service: {{service}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Destroy Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"vendor:connectionpool_.*_destroy_total\",service=~`[[service]]`}",
       "legendFormat": "name: {{__name__}} service: {{service}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Managed Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"vendor:connectionpool_.*_managed_connections\",service=~`[[service]]`}",
       "legendFormat": "name: {{__name__}} service: {{service}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"vendor:session_.*_active_sessions\",service=~`[[service]]`}",
       "legendFormat": "name: {{__name__}} service: {{service}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Live  Sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"vendor:session_.*_live_sessions\",service=~`[[service]]`}",
       "legendFormat": "name: {{__name__}} service: {{service}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threadpools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"vendor:threadpool_.*_active_threads\",service=~`[[service]]`}",
       "legendFormat": "name: {{__name__}} service: {{service}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Threadpool Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"vendor:threadpool_.*_size\",service=~`[[service]]`}",
       "legendFormat": "name: {{__name__}} service: {{service}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time per Global GC Cycle [[dur]] moving average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(base:gc_global_time_seconds{service=~`[[service]]`}[[dur]]) / rate(base:gc_global_count{service=~`[[service]]`}[[dur]])",
       "legendFormat": "service: {{service}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Time per Scavenge GC Cycle [[dur]] moving average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(base:gc_scavenge_time_seconds{service=~`[[service]]`}[[dur]]) / rate(base:gc_scavenge_count{service=~`[[service]]`}[[dur]])",
       "legendFormat": "service: {{service}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other JVM Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Uptime",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "base:jvm_uptime_seconds{service=~`[[service]]`}"
      }
     ]
    }
   ]
  }
 ]
}