{
 "title": "Liberty-Metrics-M2-G5-20190521",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": "base_cpu_processCpuLoad_percent"
   },
   {
    "name": "servlet",
    "query": "vendor_servlet_responseTime_total_seconds"
   },
   {
    "name": "dur",
    "label": "moving average",
    "query": "[1m],[5m],[10m],[30m],[1h],[1d],[7d]"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available CPU Processors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "base_cpu_availableProcessors{pod=~`[[pod]]`}",
       "legendFormat": "pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "CPU Load Percent",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "base_cpu_processCpuLoad_percent{pod=~`[[pod]]`}",
       "legendFormat": "pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "CPU System Load Average",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "base_cpu_systemLoadAverage{pod=~`[[pod]]`}",
       "legendFormat": "pod: {{pod}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Maximum Heap Size",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "base_memory_maxHeap_bytes{pod=~`[[pod]]`}"
      }
     ]
    },
    {
     "title": "Heap Usage Percentage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "base_memory_usedHeap_bytes{pod=~`[[pod]]`} / base_memory_maxHeap_bytes{pod=~`[[pod]]`}",
       "legendFormat": "pod: {{pod}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Servlets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "vendor_servlet_request_total{pod=~`[[pod]]`}"
      }
     ]
    },
    {
     "title": "Request Count for [[servlet]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_servlet_request_total{servlet=`[[servlet]]`, pod=~`[[pod]]`}",
       "legendFormat": "pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Response Time for [[servlet]] [[dur]] moving average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_servlet_responseTime_total_seconds{servlet=`[[servlet]]`,pod=~`[[pod]]`}[[dur]])/rate(vendor_servlet_request_total{servlet=`[[servlet]]`,pod=~`[[pod]]`}[[dur]])",
       "legendFormat": "pod: {{pod}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_freeConnections{pod=~`[[pod]]`}",
       "legendFormat": "datasource: {{datasource}} pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Connection Handles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_connectionHandles{pod=~`[[pod]]`}",
       "legendFormat": "datasource: {{datasource}} pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Create Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_create_total{pod=~`[[pod]]`}",
       "legendFormat": "datasource: {{datasource}} pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Destroy Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_destroy_total{pod=~`[[pod]]`}",
       "legendFormat": "datasource: {{datasource}} pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Managed Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_managedConnections{pod=~`[[pod]]`}",
       "legendFormat": "datasource: {{datasource}} pod: {{pod}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_session_activeSessions{pod=~`[[pod]]`}",
       "legendFormat": "appname: {{appname}} pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Live  Sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_session_liveSessions{pod=~`[[pod]]`}",
       "legendFormat": "appname: {{appname}} pod: {{pod}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threadpools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_threadpool_activeThreads{pod=~`[[pod]]`}",
       "legendFormat": "pool: {{pool}} pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Threadpool Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_threadpool_size{pod=~`[[pod]]`}",
       "legendFormat": "pool: {{pool}} pod: {{pod}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time per Global GC Cycle [[dur]] moving average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(base_gc_time_seconds{pod=~`[[pod]]`,name=\"global\"}[[dur]]) / rate(base_gc_total{pod=~`[[pod]]`,name=\"global\"}[[dur]])",
       "legendFormat": "pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Time per Scavenge GC Cycle [[dur]] moving average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(base_gc_time_seconds{pod=~`[[pod]]`,name=\"scavenge\"}[[dur]]) / rate(base_gc_total{pod=~`[[pod]]`,name=\"scavenge\"}[[dur]])",
       "legendFormat": "pod: {{pod}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other JVM Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Uptime",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "base_jvm_uptime_seconds {pod=~`[[pod]]`}"
      }
     ]
    }
   ]
  }
 ]
}