apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: open-liberty-operator
    app.kubernetes.io/name: open-liberty-operator
    control-plane: controller-manager
  name: olo-controller-manager
  namespace: open-liberty
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: open-liberty-operator
      app.kubernetes.io/name: open-liberty-operator
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/instance: open-liberty-operator
        app.kubernetes.io/name: open-liberty-operator
        control-plane: controller-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
      - args:
        - --health-probe-bind-address=:8081
        - --enable-leader-election
        command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_LIBERTY_SAMPLE_APP
          value: icr.io/appcafe/open-liberty/samples/getting-started@sha256:6bf52d536e94d6aa6eaa3ca9639e0fe9f5e71dbd891c50362939dd6aca519d02
        - name: RELATED_IMAGE_OPEN_LIBERTY_OPERATOR
          value: icr.io/appcafe/open-liberty-operator@sha256:d45c296d43dc4c4100f38bb736f073e04c8b4d72b68ddf1189e311aff8ad66e3
        image: icr.io/appcafe/open-liberty-operator@sha256:d45c296d43dc4c4100f38bb736f073e04c8b4d72b68ddf1189e311aff8ad66e3
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: manager
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: olo-controller-manager
      terminationGracePeriodSeconds: 10
