apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: liberty-proxy-role
  namespace: open-liberty-operator
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - create
      - get
      - update
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - update
      - list
      - watch
  - apiGroups:
      - cert-manager.io
    resources:
      - issuers
      - certificates
    verbs:
      - create
      - delete
      - get
      - update
      - list
      - watch