apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: liberty-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: liberty-proxy-role
subjects:
  - kind: ServiceAccount
    name: liberty-proxy
    namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system

