apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


bases:
- ../../overlays/watch-another-namespace

patchesStrategicMerge:
- olo-deployment.yaml
- olo-roles.yaml
- olo-sa.yaml
- watched-roles.yaml
