apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: olo-ns2

bases:
- ../../../overlays/watch-another-namespace

patchesStrategicMerge:
- olo-deployment.yaml
- olo-roles.yaml
- olo-sa.yaml
