apiVersion: apps/v1
kind: Deployment
metadata:
  name: olo-controller-manager
  namespace: olo-ns
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: WATCH_NAMESPACE
              value: olo-watched-ns2
