apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openlibertydumps.openliberty.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=='Started')].status
    description: Indicates if dump operation has started
    name: Started
    type: string
  - JSONPath: .status.conditions[?(@.type=='Completed')].status
    description: Indicates if dump operation has completed
    name: Completed
    type: string
  group: openliberty.io
  names:
    kind: OpenLibertyDump
    listKind: OpenLibertyDumpList
    plural: openlibertydumps
    singular: openlibertydump
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: OpenLibertyDump is the Schema for the openlibertydumps API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: OpenLibertyDumpSpec defines the desired state of OpenLibertyDump
          properties:
            include:
              items:
                type: string
              type: array
            podName:
              type: string
          required:
          - podName
          type: object
        status:
          description: OpenLibertyDumpStatus defines the observed state of OpenLibertyDump
          properties:
            conditions:
              items:
                description: OperationStatusCondition ...
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  lastUpdateTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    description: OperationStatusConditionType ...
                    type: string
                type: object
              type: array
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
