kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-liberty-operator
subjects:
- kind: ServiceAccount
  name: open-liberty-operator
  namespace: OPEN_LIBERTY_OPERATOR_NAMESPACE
roleRef:
  kind: ClusterRole
  name: open-liberty-operator
  apiGroup: rbac.authorization.k8s.io