apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: openliberty-app-sample
spec:
  applicationImage: icr.io/appcafe/open-liberty/samples/getting-started@sha256:323580e543429bd299f127c8956aaf319a670bce619510d3ebb67282afabb514
  expose: true
  manageTLS: true
  replicas: 1
  serviceAccount:
    mountToken: true
