apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: olo-watched-rolebinding
  namespace: olo-watched-ns
subjects:
- kind: ServiceAccount
  name: olo-controller-manager
  namespace: olo-ns2
