apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../rbac

namePrefix: olo-cluster-

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/instance: open-liberty-operator
  app.kubernetes.io/name: open-liberty-operator

patches:
- path: patches/delete-service-account.yaml
  target:
    kind: ServiceAccount

patchesJson6902:
  - target:
      namespace: open-liberty-operator
      name: .*
    patch: |-
      - op: remove
        path: /metadata/namespace
  - target:
      kind: Role
      name: .*
    patch: |-
      - op: replace
        path: /kind
        value: ClusterRole
  - target:
      kind: RoleBinding
      name: .*
    patch: |-
      - op: replace
        path: /kind
        value: ClusterRoleBinding
  - target:
      kind: ClusterRoleBinding
      name: .*
    patch: |-
      - op: replace
        path: /subjects/0/name
        value: olo-controller-manager
      - op: replace
        path: /subjects/0/namespace
        value: OPEN_LIBERTY_OPERATOR_NAMESPACE
      - op: replace
        path: /roleRef/kind
        value: ClusterRole
  - target:
      kind: ClusterRoleBinding
      name: olo-cluster-leader-election-rolebinding
    patch: |-
      - op: replace
        path: /roleRef/name
        value: olo-cluster-leader-election-role
  - target:
      kind: ClusterRoleBinding
      name: olo-cluster-manager-rolebinding
    patch: |-
      - op: replace
        path: /roleRef/name
        value: olo-cluster-manager-role
  - target:
      kind: ClusterRole
      name: olo-cluster-manager-role
    patch: |-
      - op: add
        path: /rules/-
        value: {"apiGroups":[""],"resources":["namespaces"],"verbs":["get","list","watch"]}
  - target:
      kind: ClusterRoleBinding
      name: olo-cluster-liberty-proxy-rolebinding
    patch: |-
      - op: replace
        path: /subjects/0/name
        value: olo-liberty-proxy