# Labels to add to all resources and selectors.
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: open-liberty-operator
    app.kubernetes.io/name: open-liberty-operator
resources:
- ../../crd