apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../rbac
- ../../manager

# Adds namespace to all resources.
namespace: default
namePrefix: olo-

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/instance: open-liberty-operator
  app.kubernetes.io/name: open-liberty-operator

patchesStrategicMerge:
- patches/delete-namespace.yaml
- patches/watch-namespace.yaml
